cron: &base
  build: .
  volumes:
    - "./data:/data"
  environment:
    - PGHOST
    - PGUSER
    - PGPASSWORD
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - DATABASE
    - AWS_S3_BUCKET

backup_s3:
  <<: *base
  build: .
  command: /scripts/backup-s3.sh

backup_postgres:
  <<: *base
  build: .
  command: /scripts/backup-postgres.sh
